services:
  mlops-api:
    image: mariokroll/mlops-api-sinerror
    container_name: mlops-api
    ports:
      - 6000:5000
    restart: always

  mlops-web:
    image: mariokroll/mlops-web-sinerror
    container_name: mlops-web
    ports:
      - 8080:8501
    environment:
      - API_URL=http://mlops-api:5000/predict
    depends_on:
      - mlops-api
    restart: always
