apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-web-sinerror
  labels:
    app: mlops-web-sinerror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-web-sinerror
  template:
    metadata:
      labels:
        app: mlops-web-sinerror
    spec:
      containers:
      - name: mlops-web-sinerror
        image: gcr.io/icai2025/xxx:latest 
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: http://mlops-api-service:5000/predict 