apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-web-sinerror
  labels:
    app: mlops-web-sinerror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-web
  template:
    metadata:
      labels:
        app: mlops-web
    spec:
      containers:
      - name: mlops-web
        image: gcr.io/pf-mlops-icai/mlops-web-sinerror:latest 
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: http://mlops-api-service:6000/predict 